### PR TITLE
Remove free floating "mutating" keyword from DangerDSL

### LINKED ISSUE #240: `make install` is failing!
After the just released 1.5.5, executing `make install` is giving this error:

```
/Users/david.roman/Development/swift/Sources/Danger/DangerDSL.swift:19:2: error: 'mutating' may only be used on 'func' declarations
 mutating
 ^~~~~~~~
```

It's failing to build on CI for me as well, we should try to hotfix asap.

### PR DESCRIPTION
**Pull request by sunshinejr**
Fixes #240. Hopefully! 😄

### CODE REVIEW

**Comment by davdroman** [comment]
Great response time @sunshinejr! 😄

**Comment by f-meloni** [comment]
Amazing, thank you :)

**Comment by f-meloni** [comment]
merge on green

**Comment by sunshinejr** [comment]
haha, just tried to be as fast as you with your issue timing @davdroman! love it that you can do these kinds of PRs straight from the GitHub web app and so it can be done in seconds.

**Comment by f-meloni** [comment]
Apparently I had it in my local git (not sure why), and with the add . of `Rocket` it entered by mistake in the release... Sorry :(

File: Sources/Danger/DangerDSL.swift [hunk 1]
```diff
@@ -16,7 +16,6 @@ public struct DangerDSL: Decodable {
     public private(set) var github: GitHub!
 
     public let bitbucketServer: BitBucketServer!
- mutating
```
Comment (DangerCI) [inline Sources/Danger/DangerDSL.swift]: - :warning: Lines should not have trailing whitespace. (`trailing_whitespace`)

**Comment by f-meloni** [comment]
I should definetly add a flag to `Rocket` to ensure the git status is clean before start

**Comment by f-meloni** [comment]
Ok looks good, not waiting for brew in CI because it wouldn't pass anyway

**Comment by sunshinejr** [comment]
hey @f-meloni no worries, happens to everyone! we had similar problems for Moya 12 where we had to do a quick 12.0.1 release 😅
